services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - '127.0.0.1:4566:4566'
      - '127.0.0.1:4510-4559:4510-4559'
      - '127.0.0.1:14566:14566' # テスト用ポート
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-1
      MAIN_CONTAINER_NAME: localstack
      HOSTNAME: localstack
      HOSTNAME_EXTERNAL: localstack
      # # 永続化設定
      # PERSISTENCE: 1
      # PERSISTENCE_BACKEND: filesystem
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      # # LocalStackデータの永続化
      # - ./localstack-data:/var/lib/localstack
    networks:
      - default
    restart: always

  # CLI Client
  localstack_client:
    build:
      context: .docker/ubuntu
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 20 # Node.jsバージョンを指定
        PYTHON_VERSION: 3.12 # Pythonバージョンを指定
    container_name: localstack_client
    hostname: localstack_client
    restart: always
    volumes:
      - ./workspace:/home/ubuntu/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    environment:
      TZ: Asia/Tokyo
      AWS_ENDPOINT_URL: http://localstack:4566
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-1
    networks:
      - default
    command: >
      sh -c "echo 'alias aws=\"aws --endpoint-url=$$AWS_ENDPOINT_URL\"' >> ~/.bashrc && exec bash"

# ネットワーク
networks:
  default:
    driver: bridge
